# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-04 19:38
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeoDashDashboard',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('slug', models.CharField(blank=True, max_length=255, null=True)),
                ('template', models.CharField(blank=True, max_length=255, null=True)),
                ('center', django.contrib.gis.db.models.fields.PointField(null=True, srid=4326, verbose_name=b'Center')),
            ],
            options={
                'ordering': ('title',),
                'verbose_name': 'GeoDash Maps',
                'verbose_name_plural': 'GeoDash Maps',
            },
        ),
    ]
