# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-05 15:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geodashserver', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='geodashdashboard',
            options={'ordering': ('title',), 'verbose_name': 'GeoDash Dashboards', 'verbose_name_plural': 'GeoDash Dashboards'},
        ),
    ]
