# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-07 08:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geodashserver', '0002_auto_20160605_1521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geodashdashboard',
            name='template',
        ),
        migrations.AddField(
            model_name='geodashdashboard',
            name='config',
            field=models.TextField(blank=True, null=True),
        ),
    ]
